### ISSUE TITLE
Login Documentation has typo redirectUrl should be redirect_url

### ISSUE THREAD

**Issue by mkotamies** [wkh237/react-native-azure-ad#48]
### Explanation: README.md Documentation has typo
Login Documentation has typo redirectUrl should be redirect_url. correct spelling is redirect_url. 

### Explanation: README.md ADConfig has typo
redirect_uri should be redirect_url

These typos should be corrected because they misguide users

**Comment by jongoncalves** [comment]
Technically it's `redirect_uri`. Agreed however, these typos cause confusion.

**Comment by msardi23** [comment]
The underlying code this is still incorrect though. In the `_getLoginUrl` method in `ADLoginView.js` this is still hardcoded to use the `redirect_url` parameter instead of `redirect_uri`. As such whatever you configure as the redirect_uri param in the ReactNativeAD configuration is ignored. 

You may not notice this behaviour if your app id only has one redirect registered, but I picked it up as the app id I was using has multiple redirect uri's configured and it was not select the one I had specified.

`  
(redirect ? `&**redirect_url=**${context.getConfig().redirect_uri}&nonce=rnad-${Date.now()}` : 
        
`
